FROM golang:1.20

ENV VERSION v0.0.44
ENV GOCACHE /tmp
WORKDIR /go/src/github/paulappz/movies-parser

RUN wget https://github.com/sonatype-nexus-community/nancy/releases/download/$VERSION/nancy-darwin.amd64-$VERSION -O nancy && \
    chmod +x nancy && mv nancy /usr/local/bin/nancy

RUN go install -u golang.org/x/lint/golint

RUN go mod init

RUN go mod tidy


COPY . .

RUN go get -v 