FROM golang:1.18

ENV VERSION v0.1.17
ENV GOCACHE /tmp
WORKDIR /go/src/github/paulappz/movies-parser

RUN wget https://github.com/sonatype-nexus-community/nancy/releases/download/$VERSION/nancy-linux.amd64-$VERSION -O nancy && \
    chmod +x nancy && mv nancy /usr/local/bin/nancy

RUN go install golang.org/x/lint/golint@latest

RUN go mod init

RUN go mod tidy


COPY . .

RUN go get -v 